name: SemCom-env

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - accelerate
  - datasets
  - gh
  - git
  - ipywidgets
  - jupyter-ai
  - jupyterlab
  - jupyterlab-git
  - jupyterlab-nvdashboard
  - jupyterlab-lsp
  - pip
  - pip:
    - -r requirements.txt
  - pyarrow
  - python=3.10.0
  - python-dotenv
  - python-language-server
  - pytorch==2.4.1 
  - cudatoolkit=11.8
  - pytorch-lightning
  - tensorboard
  - torchmetrics
  - transformers
  - torchvision
  - wandb
  
